Library/Models/FormViewModel.cs
using static Library.DAL.Enum;

namespace Library.WEB.Models
{
  public class FormViewModel
  {
    public int Id { get; set; }
    public Section Section { get; set; }
    public string Comment { get; set; }
    public bool isConfirmed { get; set; }
  }
}

Library/Controllers/FormController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using Library.BLL.DTO;
using Library.BLL.Infrastructure;
using Library.BLL.Interfaces;

namespace Library.WEB.Controllers
{
  public class FormController : Controller
  {
    //private IFormService formService = new FormService();
    private IFormService formService;
    private INotificationService notificationService;
    public FormController(IFormService serv, INotificationService not)
    {
      formService = serv;
      notificationService = not;
    }

    Dictionary<string, string> results = new Dictionary<string, string>();

    // GET
    [HttpGet]
    public ActionResult Index()
    {
      return View(new FormDTO());
    }
    [HttpPost]
    public  ActionResult Index(FormDTO _form)
    {
      try
      {
        formService.AddForm(_form);
        notificationService.SendEmail(_form.Email,"Message from Hub !", _form.Comment);
        return View("FormResult", _form);
      }
      catch (ValidationException ex)
      {
        //return Content(ex.Message);
        ModelState.AddModelError(ex.Property, ex.Message);
      }
      return View(_form);

    }

    [HttpPost]
    public async Task<JsonResult> IsCommentExists(string comment)
    {
      return Json(await formService.SearchComment(comment), JsonRequestBehavior.AllowGet);
    }

    protected override void Dispose(bool disposing)
    {
      formService.Dispose();
      base.Dispose(disposing);
    }
  }
}

Library/Views/Form/FormResult.cshtml
@using Library.BLL.Infrastructure.Helpers
@model Library.BLL.DTO.FormDTO
@{
  Layout = "~/Views/Shared/_Layout.cshtml";
}
  <div class="col-3-9">

    <h3>Спасибо за обращение!</h3>
    <ul>
      <li>
        @Html.LabelFor(m=>m.Comment)
        @Html.DisplayFor(Model => Model.Comment)
      </li>
      <li>
        @Html.LabelFor(m=>m.Section)
        @Html.DisplayFor(Model => Model.Section)
      </li>
      <li>
        @Html.LabelFor(m=>m.Email)
        @Html.DisplayFor(Model => Model.Email)
      </li>
      <li>
        @Html.ActionLink("Go Home", "Index", "Home")
      </li>
    </ul>
  </div>


@*@argsList.ElementAt(5).ToString()*@
@*@foreach (var res in ViewData.Keys)
  {
      TagBuilder li = new TagBuilder("li");
      li.SetInnerText(res);
      <li>@li</li>
  }*@

@section Footer{
  Все права защищены. Никита Варламов @DateTime.Now
}

Library/Views/Form/Index.cshtml
@model Library.BLL.DTO.FormDTO

@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}
  <div class="col-3-9">
    <h2>Send Form</h2>

    @using (Html.BeginForm("Index", "Form", FormMethod.Post, new { @class = "col-5-8" }))
    {
      <div class="formGrid">
        <div class="formGrid-1-1">
          @Html.LabelFor(model => model.Section, "Самый красивый раздел?", htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
        <div class="formGrid-1-2">
          @Html.EnumDropDownListFor(model => model.Section, "--Самый красивый раздел--", htmlAttributes: new { @class = "form-control" })
          @Html.ValidationMessageFor(model => model.Section, "", new { @class = "text-danger" })
        </div>
        <div class="formGrid-2-1">
          @Html.LabelFor(model => model.Comment, "Комментарий", htmlAttributes: new { @class = "control-label col-md-2", @pattern = "^[a-z A-Z]+" })
        </div>
        <div class="formGrid-2-2">
          @Html.TextAreaFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control", @placeholder = "Этот сайт классный потом что..." } })
          @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })

        </div>
        <div class="formGrid-5-1">
          @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2", @pattern = "^[a-z A-Z]+" })
        </div>
        <div class="formGrid-5-2">
          @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "sample@mail.com" } })
          @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
        <div class="formGrid-3-1">
          @Html.Label("Confirm", "Подтверждаю обработку персональных данных")
        </div>
        <div class="formGrid-3-2">
          @Html.CheckBoxFor(model => model.isConfirmed, new { @checked = "false", @type = "checkbox", @class="custom-control-input", @id="customControlInline"})
          @*@Html.ValidationMessageFor(model => model.isConfirmed, "", new { @class = "text-danger" })*@
          @Html.ValidationMessage("isConfirmed")
        </div>
        <div class="formGrid-4-1">
          @Html.ValidationSummary()
          <input type="submit" value="Отправить" />
        </div>
        <div class="formGrid-4-2">

        </div>
      </div>
    }

  </div>


@section Scripts {
  @*@Scripts.Render("~/bundles/jquery")*@
}