Library/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Library.BLL.DTO;
using Library.BLL.Interfaces;
using Library.WEB.Models;

namespace Library.WEB.Controllers
{
  [Authorize(Roles = "admin")]
  public class AdminController : Controller
  {
    private IAdminService adminService;
    private IArticleService articleService;
    private readonly IReviewService reviewService;
    private ITagService tagService;

    private readonly MapperConfiguration configReviewToReviewDTO = new MapperConfiguration(cfg => cfg
      .CreateMap<ReviewDTO, ReviewViewModel>()
      .ForMember("Author", opt => opt.MapFrom(rDto => rDto.ApplicationUser.UserName))
      .ForMember("Comment", opt => opt.MapFrom(rDto => rDto.Comment))
      .ForMember("Rate", opt => opt.MapFrom(rDto => rDto.Rate))
      .ForMember("DateOfCreation", opt => opt.MapFrom(rDto => rDto.DateCreation.Date.ToString("d"))));

    private readonly MapperConfiguration configTagToView = new MapperConfiguration(cfg => cfg
      .CreateMap<TagDTO, TagViewModel>());


    public AdminController(IAdminService adServ, IArticleService artServ, IReviewService revServ, ITagService tagServ)
    {
      adminService = adServ;
      articleService = artServ;
      reviewService = revServ;
      tagService = tagServ;
    }

    public ActionResult Index()
    {
      return View();
    }

    public async Task<ActionResult> Comments(int? id)
    {
      var mapper = new Mapper(configReviewToReviewDTO);
      IEnumerable<ReviewViewModel> reviews = mapper.Map<IEnumerable<ReviewViewModel>>(await reviewService.GetReviewsByDateAsyncAsTask(1));
      switch (id)
      {
        case 1:
        {
          break;
        }
        case 0:
        {
          reviews = mapper.Map<IEnumerable<ReviewViewModel>>(await reviewService.GetReviewsByDateAsyncAsTask(0));
          break;
        }
      }

      return View(reviews);
    }

    public async Task<ActionResult> Tags(int? id)
    {
      var mapper = new Mapper(configTagToView);
      var tags = mapper.Map<IEnumerable<TagViewModel>>(await tagService.GetTagsSorted(id));
      return View(tags);
    }

  }
}

Library/Controllers/GuestController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Library.BLL.DTO;
using Library.BLL.Infrastructure;
using Library.BLL.Interfaces;

namespace Library.WEB.Controllers
{
  public class GuestController : Controller
  {
    //private ReviewService reviewService = new ReviewService(); 
    /// <summary>
    /// Вот сюда система (не ниджект) подставит конскретную реалтзацию
    /// этого сервиса, который мы забиндили в global.asax
    /// Теперь если мі захотим поменять к примеру реализацию сервиса 
    /// ReviewService на NewReviewService на не прийдется везде менять
    /// ReviewService на NewReviewService, мы просто перебиндим реализацию
    /// и интерфейс. 
    /// </summary>
    private IReviewService reviewService;
    public GuestController(IReviewService serv)
    {
      reviewService = serv;
    }
    // GET: Guest
    public ActionResult Index(int id)
    {
      ReviewDTO review = new ReviewDTO { ArticleId = id };
      //ViewBag.Review = review;
      ViewBag.BookId = id;
      return View(review);
    }
    [HttpGet]
    public ActionResult CommentFormPartial(int id)
    {
      //Tuple<ReviewDTO, IEnumerable<SelectListItem>> reviewRepo = 
      //  new Tuple<ReviewDTO, IEnumerable<SelectListItem>>
      //  (new ReviewDTO(), reviewService.GetSelectListItems());

      return PartialView();
    }
    [HttpPost]
    public ActionResult CommentFormPartial(ReviewDTO review)
    {
      try
      {
        reviewService.AddReview(review);
        return RedirectToAction($"Index/{review.ArticleId}");
      }
      catch (ValidationException ex)
      {
        ModelState.AddModelError(ex.Property, ex.Message);
      }
      return View("Index", review);

      //if (ModelState.IsValid)
      //{

      //}
      //else
      //{
      //  return View(review);
      //}
      ///<remarks>
      ///получаешь форму, 
      ///добавляешь туда валидационные сообщения 
      ///и возвращаешь ее обратно
      ///</remarks>
    }

    [ChildActionOnly]
    public ActionResult CommentListPartial()
    {
      List<ReviewDTO> reviews = reviewService.GetReviews() as List<ReviewDTO>;
      return PartialView(reviews);
    }
  }
}

Library/Views/Shared/LeftNavPartial.cshtml
@model IEnumerable<string>
<div class="navBarWrapper">
    @Html.CreateMenu(Model.ToArray())
</div>

Library/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - My ASP.NET Application</title>
  <link href="//fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans:ital,wght@0,600,400,300;1,400&display=swap"
        rel="stylesheet" type="text/css">
  <script src="~/Scripts/modernizr-2.8.3.js"></script>
  @Scripts.Render("~/bundles/jquery")
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  @Styles.Render("~/Content/customCss")


</head>
<body>
<nav id="introNav" class="navbar navbar-expand-lg navbar-light bg-light">
  <picture>
    <a href="@Url.Action("Index", "Home")">
      <img src="~/img/hub.png" alt="Hub logo">
    </a>
  </picture>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      @if (User.Identity.IsAuthenticated)
      {
        <li>@Html.ActionLink("Create article", "CreateArticle", "Home")</li>
      }
      <li>@Html.ActionLink("Home", "Index", "Home")</li>
      <li>@Html.ActionLink("Form", "Index", "Form")</li>
      <li class="nav-item dropdown">
        @if (!User.Identity.IsAuthenticated)
        {
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Enter?
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            @Html.ActionLink("Login", "Login", "Account", "", new { @class = "dropdown-item" })
            <div class="dropdown-divider"></div>
            @Html.ActionLink("Register", "Register", "Account", "", new { @class = "dropdown-item" })
          </div>
        }
        else
        {
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span>Hello, </span>@User.Identity.Name
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            @Html.ActionLink("Logout", "Logout", "Account", "", new { @class = "dropdown-item" })
          </div>
        }
      </li>
    </ul>
  </div>

</nav>
<nav role="navigation">
    <div id="menuToggle">
      <input type="checkbox" id="menuToggler">
      <span></span>
      <span></span>
      <span></span>
      <ul id="menu">
        <li>
          <a href=@Url.Action("Index", "Home")>
            <h3>Main</h3>
          </a>
        </li>
        <li>
          <a href=@Url.Action("CreateArticle", "Home")>
            <h3>Add new Article</h3>
          </a>
        </li>
        <li>
          <a href=@Url.Action("Index", "Form")>
            <h3>Send Reply</h3>
          </a>
        </li>
        @if (User.IsInRole("admin"))
        {
          <li>
            <a href=@Url.Action("Index", "Admin")>
              <h3>Admin Page</h3>
            </a>
          </li>

        }
        @if (User.Identity.IsAuthenticated)
        {
          <li>
            <a href=@Url.Action("CreateArticle", "Home")>
              <h3>Create an Article</h3>
            </a>
          </li>
        }
        <li>
          <a href=@Url.Action("Index", "Home")>
            <h3>Go Home</h3>
          </a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="mainGrid">
    @RenderBody()

  </div>
  <footer>
    @RenderSection("Footer", false)
    Все права защищены. Никита Варламов @DateTime.Now.Year
  </footer>
  @RenderSection("scripts", false)


  @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
  @*<script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
  @Scripts.Render("~/bundles/bootstrap")
  @Scripts.Render("~/bundles/jqueryval")
</body>
</html>

Library/Views/Shared/_Layout_Admin.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@ViewBag.Title - My ASP.NET Application</title>
  <link href="//fonts.googleapis.com/css2?family=Lato&family=Montserrat&family=Open+Sans:ital,wght@0,600,400,300;1,400&display=swap"
        rel="stylesheet" type="text/css">
  <script src="~/Scripts/modernizr-2.8.3.js"></script>
  @Scripts.Render("~/bundles/jquery")
  @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")
  @Styles.Render("~/Content/customCss")


</head>
<body>
<nav id="introNav" class="navbar navbar-expand-lg navbar-light bg-light">
  <picture>
    <a href="@Url.Action("Index", "Home")">
      <img src="~/img/book.svg" alt="">
    </a>
  </picture>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li>@Html.ActionLink("Главная", "Index", "Home")</li>
      <li>@Html.ActionLink("Гостевая", "Index/0", "Guest")</li>
      <li>@Html.ActionLink("Форма", "Index", "Form")</li>
      <li class="nav-item dropdown">
        @if (!User.Identity.IsAuthenticated)
        {
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Enter?
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            @Html.ActionLink("Login", "Login", "Account", "", new { @class = "dropdown-item" })
            <div class="dropdown-divider"></div>
            @Html.ActionLink("Register", "Register", "Account", "", new { @class = "dropdown-item" })
          </div>
        }
        else
        {
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span>Hello, </span>@User.Identity.Name
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            @Html.ActionLink("Logout", "Logout", "Account", "", new { @class = "dropdown-item" })
          </div>
        }
      </li>
    </ul>
  </div>

</nav>
<nav role="navigation">
    <div id="menuToggle">
      <input type="checkbox" id="menuToggler">
      <span></span>
      <span></span>
      <span></span>
      <ul id="menu">
        <li>
          <a href=@Url.Action("Index", "Home")>
            <h3>Main</h3>
          </a>
        </li>
        <li>
          <a href=@Url.Action("CreateArticle", "Home")>
            <h3>Add new Article</h3>
          </a>
        </li>
        <li>
          <a href=@Url.Action("Index", "Form")>
            <h3>Send Reply</h3>
          </a>
        </li>
        <li>
          <a href=@Url.Action("Logout", "Account")>
            <h3>Наши проекты</h3>
          </a>
        </li>
        <li>
          <a href="#newsSection">
            <h3>Новости</h3>
          </a>
        </li>
        <li>
          <a href="#wordrobeSection">
            <h3>Гардероб</h3>
          </a>
        </li>
        <li>
          <a href="#contactsSection">
            <h3>Контакты</h3>
          </a>
        </li>

      </ul>
    </div>
  </nav>

  <div class="mainGrid">
    @RenderBody()

  </div>
  <footer>
    @RenderSection("Footer", false)
    Все права защищены. Никита Варламов @DateTime.Now.Year
  </footer>
  @RenderSection("scripts", false)


  @*<script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
  @*<script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>*@
  @Scripts.Render("~/bundles/bootstrap")
  @Scripts.Render("~/bundles/jqueryval")
</body>
</html>

Library/Views/Shared/_Layoutt.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>