Library/Models/TagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Library.WEB.Models
{
  public class TagViewModel
  {
    public int Id { get; set; }
    public string Name { get; set; }
  }
}

Library/Controllers/TagController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Library.BLL.DTO;
using Library.BLL.Interfaces;
using Library.WEB.Models;

namespace Library.WEB.Controllers
{
  public class TagController : Controller
  {
    private readonly MapperConfiguration configTag = new MapperConfiguration(cfg => cfg
      .CreateMap<TagDTO, TagViewModel>());

    private readonly ITagService tagService;

    public TagController(ITagService tagServ)
    {
      tagService = tagServ;
    }

    [Authorize(Roles = "admin")]
    public async Task<ActionResult> EditTag(int id)
    {
      var mapper = new Mapper(configTag);
      if (id == null)
        return HttpNotFound();
      var tagDTO = await tagService.GetTagByIdAsTask(id);
      if (tagDTO != null)
      {
        var tagViewModel = new TagViewModel
        {
          Id = tagDTO.Id,
          Name = tagDTO.Name
        };
        return View(tagViewModel);
      }

      return HttpNotFound();
    }

    [Authorize(Roles = "admin")]
    [HttpPost]
    public async Task<ActionResult> EditTag(TagViewModel tagViewModel)
    {
      var tagDto = new TagDTO
      {
        Id = tagViewModel.Id,
        Name = tagViewModel.Name
      };
      tagService.EditTag(tagDto);
      return RedirectToAction("Tags", "Admin");
    }
  }
}

Library/Views/Tag/EditTag.cshtml
@model Library.WEB.Models.TagViewModel

@{
    ViewBag.Title = "EditTag";
    Layout = "~/Views/Shared/_Layout_Admin.cshtml";
}
  <div class="col-3-9">
    <h2>EditTag</h2>

    @using (Html.BeginForm("EditTag", "Tag", FormMethod.Post))
    {
      @Html.AntiForgeryToken()

  <div class="form-horizontal">
    <hr />
    @Html.HiddenFor(m => m.Id)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Save changes" class="btn btn-default" />
      </div>
    </div>
  </div>
    }

    <div>
      @Html.ActionLink("Back to List", "Tags", "Admin")
    </div>
  </div>